export let exerciseList = [
	{ name: "dumbbell curl", imgSrc: "ex2 dumbbell curl.png", score: 0 },
	{ name: "lying leg raise", imgSrc: "ex3 lying leg raise.png", score: 0 },
	{ name: "standing knee up", imgSrc: "ex6 standing knee up.png", score: 0 },
	{ name: "side lunge", imgSrc: "ex5 side lunge.png", score: 0 },
	{ name: "side lateral raise", imgSrc: "ex4 side lateral raise.png", score: 0 },
	{ name: "standing side crunch", imgSrc: "ex7 standing side crunch.png", score: 0 },
	{ name: "twist crunch", imgSrc: "ex15 twist crunch.png", score: 0 },
	{ name: "plank", imgSrc: "ex9 plank.png", score: 0 },
	{ name: "russian twist", imgSrc: "ex11 russian twist.png", score: 0 },
	{ name: "decline pushup", imgSrc: "ex14 decline push up.png", score: 0 },
	{ name: "mountain climber", imgSrc: "ex10 mountain climber.png", score: 0 },
	{ name: "leg bridge", imgSrc: "ex13 leg bridge.png", score: 0 },
	{ name: "babel squat", imgSrc: "ex1 babel squat.png", score: 0 },
	{ name: "hindu push up", imgSrc: "ex12 hindu push up.png", score: 0 },
	{ name: "crunch", imgSrc: "ex8 crunch.png", score: 0 },
];
