# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn
    - run: yarn build
      env:
        CI: false
        # PUBLIC_URL: https://${{ github.repository_owner }}.github.io/kwix-web/
        REACT_APP_SERVER_URL: ${{ secrets.SERVER_URL }}
#     - run: npm test
    # - name: Deploy 🚀
    #   uses: JamesIves/github-pages-deploy-action@v4.3.3
    #   with:
    #     branch: gh-pages # The branch the action should deploy to.
    #     folder: build # The folder the action should deploy.
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: web-static-file
        path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: web-static-file
          path: build
      - name: check file
        run: ls -R
      - name: Netlify Deploy
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}